package com.ethioride.shared.protocol;

public enum MessageType {
    // Auth
    LOGIN_REQUEST,
    LOGIN_RESPONSE,
    REGISTER_REQUEST,
    REGISTER_RESPONSE,

    // Trip lifecycle
    TRIP_REQUEST,
    TRIP_ACCEPTED,
    TRIP_DECLINED,
    TRIP_STARTED,
    TRIP_COMPLETED,
    TRIP_CANCELLED,

    // Driver
    DRIVER_LOCATION_UPDATE,
    DRIVER_STATUS_UPDATE,

    // Admin - User Management
    USER_LIST_REQUEST,
    USER_LIST_RESPONSE,
    USER_CREATE_REQUEST,
    USER_CREATE_RESPONSE,
    USER_DELETE_REQUEST,
    USER_DELETE_RESPONSE,

    // Admin - Trips & Stats
    TRIP_LIST_REQUEST,
    TRIP_LIST_RESPONSE,
    DASHBOARD_STATS_REQUEST,
    DASHBOARD_STATS_RESPONSE,

    // Driver - Trip History & Earnings
    DRIVER_TRIP_HISTORY_REQUEST,
    DRIVER_TRIP_HISTORY_RESPONSE,
    DRIVER_EARNINGS_REQUEST,
    DRIVER_EARNINGS_RESPONSE,

    // Passenger - Trip History
    PASSENGER_TRIP_HISTORY_REQUEST,
    PASSENGER_TRIP_HISTORY_RESPONSE,

    // Financial Reports
    FINANCIAL_REPORT_REQUEST,
    FINANCIAL_REPORT_RESPONSE,

    // Driver locations for map
    DRIVER_LOCATIONS_REQUEST,
    DRIVER_LOCATIONS_RESPONSE,

    // Pricing
    PRICE_ESTIMATE_REQUEST,
    PRICE_ESTIMATE_RESPONSE,
    PRICING_RULES_REQUEST,
    PRICING_RULES_RESPONSE,
    PRICING_RULES_UPDATE,
    PRICING_RULES_UPDATE_RESPONSE,

    // Matchmaking
    MATCH_NOTIFY_DRIVER,

    // System
    HEARTBEAT,
    ERROR,
    ACK
}
