package com.ethioride.shared.protocol;

public enum MessageType {
    // Auth
    LOGIN_REQUEST,
    LOGIN_RESPONSE,
    REGISTER_REQUEST,
    REGISTER_RESPONSE,
    LOGOUT,

    // Trip lifecycle
    TRIP_REQUEST,
    TRIP_ACCEPTED,
    TRIP_DECLINED,
    TRIP_STARTED,
    TRIP_COMPLETED,
    TRIP_CANCELLED,

    // Driver
    DRIVER_LOCATION_UPDATE,
    DRIVER_STATUS_UPDATE,

    // Admin - User Management
    USER_LIST_REQUEST,
    USER_LIST_RESPONSE,
    USER_CREATE_REQUEST,
    USER_CREATE_RESPONSE,
    USER_DELETE_REQUEST,
    USER_DELETE_RESPONSE,

    // Admin - Trips & Stats
    TRIP_LIST_REQUEST,
    TRIP_LIST_RESPONSE,
    DASHBOARD_STATS_REQUEST,
    DASHBOARD_STATS_RESPONSE,

    // Driver - Trip History & Earnings
    DRIVER_TRIP_HISTORY_REQUEST,
    DRIVER_TRIP_HISTORY_RESPONSE,
    DRIVER_EARNINGS_REQUEST,
    DRIVER_EARNINGS_RESPONSE,

    // Pricing
    PRICE_ESTIMATE_REQUEST,
    PRICE_ESTIMATE_RESPONSE,
    PRICING_RULES_REQUEST,
    PRICING_RULES_RESPONSE,
    PRICING_RULES_UPDATE,
    PRICING_RULES_UPDATE_RESPONSE,

    // System
    HEARTBEAT,
    ERROR,
    ACK,

    // Matchmaking
    MATCH_FOUND,
    MATCH_NOTIFY_DRIVER,

    // Admin
    STATS_REQUEST,
    STATS_RESPONSE,
    DRIVERS_REQUEST,
    DRIVERS_RESPONSE,
    TRIPS_REQUEST,
    TRIPS_RESPONSE
}
